Fix type mismatch with latest FreeType
This change is intrumented due to a type change in freetype [1] with release 2.13.3

Fixes
| ../../git/src/FTVectoriser.cpp:171:15: error: cannot initialize a variable of type 'char *' with an rvalue of type 'unsigned char *'
|   171 |         char* tagList = &outline.tags[startIndex];
|       |               ^         ~~~~~~~~~~~~~~~~~~~~~~~~~

[1] https://gitlab.freedesktop.org/freetype/freetype/-/commit/044d142be7b6a93b6940367a1bc5847451ff4775

Signed-off-by: Khem Raj <raj.khem@gmail.com>